[tools]
clang = "latest"
clang-format = "latest"
"conda:compiler-rt" = "latest"
"conda:cppcheck" = "latest"
"conda:bear" = "latest"

[tasks.build]
description = "compile main (non debug)"
run = """
clang -std=c23 \
      -fblocks \
      -Wall -Wextra -Wpedantic \
      -Wshadow -Wconversion -Wdouble-promotion \
      -Wformat=2 -Wundef -fno-common \
      -O2 \
      $(find . -name '*.c' | grep -v 'test.c') \
      -o app \
      -lBlocksRuntime
"""

[tasks.dev]
description = "compile main (debug/dev build)"
run = """
clang -std=c23 \
      -fblocks \
      -Wall -Wextra -Wpedantic \
      -Wshadow -Wconversion -Wdouble-promotion \
      -Wformat=2 -Wundef \
      -ggdb -O0 \
      $(find . -name '*.c' | grep -v 'test.c') \
      -o app-dev \
      -lBlocksRuntime
"""

[tasks.test]
description = "compile tests"
run = """
clang -std=c23 \
      -fblocks \
      -Wall -Wextra -Wpedantic \
      -g -O0 \
      $(find . -name '*.c' | grep -v 'main.c') \
      -o tests \
      -lBlocksRuntime
"""

[tasks.run]
description = "run release build"
depends = ["build"]
run = "./app"

[tasks.dev-run]
description = "run debug/dev build"
depends = ["dev"]
run = "./app-dev"

[tasks.compiledb]
description = "generate compile_commands.json for neovim"
run = "bear -- append mise run build && bear -- append mise run test"

[tasks.check]
description = "check stuff"
run = "cppcheck --enable=all --suppress=missingIncludeSystem *.c"

[tasks.format]
description = "format files"
run = "clang-format -i *.c *.h"

[tasks.clean]
description = "remove build artifacts"
run = "rm -rf app app-dev tests compile_commands.json .bear-fingerprints"
